import { useQuery, useMutation, gql } from "@apollo/client";
import { useRouter } from "next/router";
import Link from "next/link";
import Head from "next/head";
import {
  PageHeader,
  Button,
  Typography,
  Modal,
  Space,
  Card,
  Skeleton,
  Descriptions,
} from "antd";
import dayjs from "dayjs";

const { Text, Title } = Typography;
const { confirm } = Modal;

const GET_FAMILIES = gql`
  query GetFamilies($id: ID!) {
    family: findFamilyByID(id: $id) {
      _id
      primaryFirstName
      primaryLastName
      secondaryFirstName
      secondaryLastName
      address
      aptNo
      city
      zip
      phone1
      phone2
      deleted
      createdAt
      children {
        data {
          _id
          firstName
          lastName
          gender
          age
          ageType
          notes
          school
          createdAt
        }
      }
    }
  }
`;

const DELETE_FAMILY = gql`
  mutation DeleteFamily($id: ID!) {
    updateFamily(id: $id, data: { deleted: true }) {
      _id
    }
  }
`;

const Gender = {
  BOY: "Boy",
  GIRL: "Girl",
};

const AgeType = {
  YEAR: "years",
  MONTH: "months",
};

export default function FamilyShow() {
  const router = useRouter();
  const { id } = router.query;
  const { loading, error, data } = useQuery(GET_FAMILIES, {
    variables: { id },
    fetchPolicy: "no-cache",
  });
  const onCompleted = () => {
    router.push(`/families/list`);
  };
  const [deleteFamily] = useMutation(DELETE_FAMILY, {
    onCompleted,
  });
  const confirmDelete = () => {
    confirm({
      title: "Are you sure you want to delete?",
      onOk() {
        deleteFamily({
          variables: { id },
        });
      },
    });
  };
  if (loading || !data) return <Skeleton active loading={loading} />;
  const {
    _id,
    primaryFirstName,
    primaryLastName,
    secondaryFirstName,
    secondaryLastName,
    address,
    aptNo,
    city,
    zip,
    phone1,
    phone2,
    createdAt,
    children,
  } = data?.family;
  return (
    <div>
      <Head>
        <title>Family - CheerFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title={`${primaryFirstName} ${primaryLastName}`}
        subTitle={
          <>
            <strong>Created: </strong> {dayjs(createdAt).format("MMM DD, YYYY")}
          </>
        }
        backIcon={false}
        extra={[
          <Link key="edit" href={`/families/edit/${_id}`}>
            <Button type="primary">Edit Family</Button>
          </Link>,
          <a
            key="full-sheet"
            target="_blank"
            rel="noreferrer"
            href={`/api/print/full-sheet/${_id}`}
          >
            <Button type="secondary">Print Full Sheet</Button>
          </a>,
          <a
            key="letter"
            rel="noreferrer"
            target="_blank"
            href={`/api/print/letter/${_id}`}
          >
            <Button type="secondary">Print Letter</Button>
          </a>,
          <Button key="remove" type="danger" onClick={confirmDelete}>
            Remove Family
          </Button>,
        ]}
      />
      <Space direction="vertical">
        <Card key={_id}>
          <Descriptions title="Family Details">
            <Descriptions.Item label="Primary Adult">
              {primaryFirstName} {primaryLastName}
            </Descriptions.Item>
            <Descriptions.Item label="Secondary Adult">
              {secondaryFirstName} {secondaryLastName}
            </Descriptions.Item>
            <Descriptions.Item label="Phone #1">{phone1}</Descriptions.Item>
            <Descriptions.Item label="Phone #2">{phone2}</Descriptions.Item>
            <Descriptions.Item label="Address">
              {address}, {aptNo} {city}, {zip}
            </Descriptions.Item>
          </Descriptions>
        </Card>
        {children.data.map((child) => {
          return (
            <Card key={child._id}>
              <Title level={4}>
                {child.firstName} {child.lastName}
              </Title>
              <Descriptions title="Child Details">
                <Descriptions.Item label="Age">
                  {child.age} {AgeType[child.ageType]}
                </Descriptions.Item>
                <Descriptions.Item label="School">
                  {child.school}
                </Descriptions.Item>
                <Descriptions.Item label="Gender">
                  {Gender[child.gender]}
                </Descriptions.Item>
                <Descriptions.Item label="Notes">
                  {child.notes}
                </Descriptions.Item>
              </Descriptions>
            </Card>
          );
        })}
      </Space>
    </div>
  );
}
