import { useState } from "react";
import { useQuery, gql } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";
import {
  Form,
  PageHeader,
  Input,
  Button,
  Checkbox,
  Typography,
  Row,
  Col,
  Divider,
  Select,
  Space,
  Card,
  Descriptions,
  Skeleton,
} from "antd";
import { PlusOutlined } from "@ant-design/icons";
import { Children } from "react/cjs/react.production.min";

const { Title } = Typography;

const ALL_FAMILIES = gql`
  query GetFamilies {
    allFamilies {
      data {
        _id
        primaryFirstName
        primaryLastName
        secondaryFirstName
        secondaryLastName
        children {
          data {
            age
          }
        }
      }
    }
  }
`;

export default function FamilyList() {
  const [search, setSearch] = useState("");
  const { loading, data } = useQuery(ALL_FAMILIES);
  return (
    <div>
      <Head>
        <title>All Families - CheerFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title="All Families"
        subTitle="List of families"
        backIcon={false}
      />
      <Skeleton active loading={loading}>
        <Space direction="vertical" style={{ width: "100%" }}>
          <Input
            onChange={(e) => setSearch(e.target.value)}
            value={search}
            placeholder="Search for a family..."
          />
          {data?.allFamilies.data
            .filter((family) => {
              if (!search) {
                return family;
              }
              return `${family.primaryFirstName}${family.primaryLastName}`
                .toLowerCase()
                .includes(search.toLowerCase());
            })
            .map((family) => {
              const {
                _id,
                primaryFirstName,
                primaryLastName,
                secondaryFirstName,
                secondaryLastName,
                children,
              } = family;
              return (
                <Card
                  key={_id}
                  actions={[
                    <Link href={`/families/${_id}`} key="view">
                      <Button>View Family</Button>
                    </Link>,
                  ]}
                >
                  <Title level={4}>
                    {primaryFirstName} {primaryLastName}
                  </Title>
                  <Descriptions>
                    <Descriptions.Item label="Secondary Adult">
                      {secondaryFirstName} {secondaryLastName}
                    </Descriptions.Item>
                    <Descriptions.Item label="Number of children">
                      {children.data.length}
                    </Descriptions.Item>
                  </Descriptions>
                </Card>
              );
            })}
        </Space>
      </Skeleton>
    </div>
  );
}
