import { useQuery, gql } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";
import {
  Form,
  PageHeader,
  Input,
  Button,
  Checkbox,
  Typography,
  Row,
  Col,
  Divider,
  Select,
  Space,
  Card,
  Skeleton,
} from "antd";
import { PlusOutlined } from "@ant-design/icons";

const { Title } = Typography;

const ALL_FAMILIES = gql`
  query GetFamilies {
    allFamilies {
      data {
        _id
        primaryFirstName
        primaryLastName
      }
    }
  }
`;

export default function FamilyList() {
  const { loading, error, data } = useQuery(ALL_FAMILIES);
  return (
    <div>
      <Head>
        <title>All Families - CheerFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title="All Families"
        subTitle="List of families"
        backIcon={false}
      />
      <Skeleton active loading={loading}>
        {data?.allFamilies.data.map((family) => {
          const { _id, primaryFirstName, primaryLastName } = family;
          return (
            <Card key={_id}>
              <Title level={4}>
                {primaryFirstName} {primaryLastName}
              </Title>
              <Link href={`/families/${_id}`}>
                <Button>View Family</Button>
              </Link>
            </Card>
          );
        })}
      </Skeleton>
    </div>
  );
}
