import { useState } from "react";
import { useQuery, useMutation, gql } from "@apollo/client";
import Head from "next/head";
import Link from "next/link";
import {
  PageHeader,
  Input,
  Button,
  Typography,
  Modal,
  Space,
  Card,
  Descriptions,
  Skeleton,
} from "antd";

const { Title } = Typography;
const { confirm } = Modal;

const ALL_FAMILIES = gql`
  query GetFamilies {
    families: familiesByDeleted(deleted: false) {
      data {
        _id
        primaryFirstName
        primaryLastName
        secondaryFirstName
        secondaryLastName
        children {
          data {
            age
          }
        }
      }
    }
  }
`;

const DELETE_FAMILY = gql`
   mutation DeleteFamily($id: ID!) {
     updateFamily(id: $id, data: { deleted: true}) {
      _id
    }
  }
`;

export default function FamilyList() {
  const [search, setSearch] = useState("");
  const { loading, data, refetch } = useQuery(ALL_FAMILIES, { fetchPolicy: "no-cache" });
  const onCompleted = () => {
    refetch();
  };
  const [deleteFamily] = useMutation(DELETE_FAMILY, {
    onCompleted,
  });
  const confirmDelete = (id) => () => {
    confirm({
      title: "Are you sure you want to delete?",
      onOk() {
        deleteFamily({
          variables: { id },
        });
      },
    });
  };
  return (
    <div>
      <Head>
        <title>All Families - CheerFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title="All Families"
        subTitle="List of families"
        backIcon={false}
      />
      <Skeleton active loading={loading}>
        <Space direction="vertical" style={{ width: "100%" }}>
          <Input
            onChange={(e) => setSearch(e.target.value)}
            value={search}
            placeholder="Search for a family..."
          />
          {data?.families.data
            .filter((family) => {
              if (!search) {
                return family;
              }
              return `${family.primaryFirstName}${family.primaryLastName}`
                .toLowerCase()
                .includes(search.toLowerCase());
            })
            .map((family) => {
              const {
                _id,
                primaryFirstName,
                primaryLastName,
                secondaryFirstName,
                secondaryLastName,
                children,
              } = family;
              return (
                <Card
                  key={_id}
                  actions={[
                    <Link href={`/families/${_id}`} key="view">
                      <Button type="primary">View Family</Button>
                    </Link>,
                    <Button type="danger" onClick={confirmDelete(_id)}>Remove Family</Button>,
                  ]}
                >
                  <Title level={4}>
                    {primaryFirstName} {primaryLastName}
                  </Title>
                  <Descriptions>
                    <Descriptions.Item label="Secondary Adult">
                      {secondaryFirstName} {secondaryLastName}
                    </Descriptions.Item>
                    <Descriptions.Item label="Number of children">
                      {children.data.length}
                    </Descriptions.Item>
                  </Descriptions>
                </Card>
              );
            })}
        </Space>
      </Skeleton>
    </div>
  );
}
