import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CheerFund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Spread the cheer!</h1>

        <div className={styles.grid}>
          <Link href="/families/new">
            <a className={styles.card}>
              <h2>New Family &rarr;</h2>
              <p>Create a new family</p>
            </a>
          </Link>

          <Link href="/families/new">
            <a className={styles.card}>
              <h2>Family List &rarr;</h2>
              <p>View all families</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
